[theme]
primaryColor = "#147B36"  

backgroundColor = "#ecf4ed"  # Clean white background

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#7FBA9D"  
font = "sans serif"  # Clean, professional font
textColor = "#393E41"


